site_name: BracketHighlighter Documentation
repo_url: https://github.com/facelessuser/BracketHighlighter
site_description: A customizable Sublime Text plugin that highlights matching brackets.
pages:
- ['index.md', 'Home']
- ['usage.md', 'User Guide']
- ['customize.md', 'Customization']
