site_name: BracketHighlighter Documentation
repo_url: https://github.com/facelessuser/BracketHighlighter
site_description: A customizable Sublime Text plugin that highlights matching brackets.
pages:
- ['index.md', 'Home']
- ['usage.md', 'User Guide']
- ['customize.md', 'Customization']
theme: readthedocs
extra_javascript:
- js/theme_custom.js
extra_css:
- css/theme_custom.css
markdown_extensions:
- markdown.extensions.extra
- markdown.extensions.admonition
- markdown.extensions.smarty
- markdown.extensions.nl2br
- pymdownx.inlinehilite(use_pygments=False)
- pymdownx.magiclink
- pymdownx.betterem
- pymdownx.tilde
- pymdownx.caret
- pymdownx.smartsymbols
- pymdownx.githubemoji
- pymdownx.tasklist
- pymdownx.superfences
- pymdownx.progressbar
